name: ci/cd frontend

on:
  workflow_dispatch:

  
jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Inicio de ci/cd 
        run: echo "Se inicia la integracion y despliegue continuo"

  llamar_ci:
    needs: ci-cd
    uses: ./.github/workflows/ci.yaml
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

  efectuar_cd_prod:
    needs: [llamar_ci]
    uses: ./.github/workflows/cd.yaml
    with: 
      imagen_docker_completa: "${{needs.llamar_ci.outputs.tag_image}}"
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}