name: ci frontend

on:
  workflow_dispatch:
    # outputs:
    #   tag_image:
    #     value: ${{ jobs.ci.outputs.imagen_docker}}

jobs:

  ci:
    runs-on: ubuntu-latest
    outputs:
      imagen_docker: ${{steps.imagen_docker1.outputs.imagen_docker}}
    steps:
      - name: clonamos repo
        uses: actions/checkout@v4

      - name: Se obtiene la version
        id: tomar_version
        run: |
          version=$(jq -r '.version' package.json)
          echo "La version del la app es: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: accion composite
        uses: ./.github/actions/taggear-imagen
        id: tag
        env:
          username: ${{ vars.DOCKER_USERNAME }}
        with:
          image_name: "frontend"
          version: "${{steps.tomar_version.outputs.version}}"

      - name: Mostrar imagen completa
        run: echo ${{ steps.tag.outputs.tag}}

      - name: Guardar output 
        id: imagen_docker1
        run: echo "imagen_docker=${{steps.tag.outputs.tag}}" >> $GITHUB_OUTPUT

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: containerregistryjoel.azurecr.io
          username: ${{ Secrets.ARM_CLIENT_ID }}
          password: ${{ secrets.ARM_CLIENT_SECRET }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.tag.outputs.tag}} 
        
      
